const countriesData = [
    {
      name: "India",
      value: "India",
      states: [
        { name: "Andhra Pradesh", value: "Andhra Pradesh" },
        { name: "Arunachal Pradesh", value: "Arunachal Pradesh" },
        { name: "Assam", value: "Assam" },
        { name: "Bihar", value: "Bihar" },
        { name: "Chhattisgarh", value: "Chhattisgarh" },
        { name: "Goa", value: "Goa" },
        { name: "Gujarat", value: "Gujarat" },
        { name: "Haryana", value: "Haryana" },
        { name: "Himachal Pradesh", value: "Himachal Pradesh" },
        { name: "Jharkhand", value: "Jharkhand" },
        { name: "Karnataka", value: "Karnataka" },
        { name: "Kerala", value: "Kerala" },
        { name: "Madhya Pradesh", value: "Madhya Pradesh" },
        { name: "Maharashtra", value: "Maharashtra" },
        { name: "Manipur", value: "Manipur" },
        { name: "Meghalaya", value: "Meghalaya" },
        { name: "Mizoram", value: "Mizoram" },
        { name: "Nagaland", value: "Nagaland" },
        { name: "Odisha", value: "Odisha" },
        { name: "Punjab", value: "Punjab" },
        { name: "Rajasthan", value: "Rajasthan" },
        { name: "Sikkim", value: "Sikkim" },
        { name: "Tamil Nadu", value: "Tamil Nadu" },
        { name: "Telangana", value: "Telangana" },
        { name: "Tripura", value: "Tripura" },
        { name: "Uttar Pradesh", value: "Uttar Pradesh" },
        { name: "Uttarakhand", value: "Uttarakhand" },
        { name: "West Bengal", value: "West Bengal" },
      ],
    },
    {
      name: "USA",
      value: "USA",
      states: [
        { name: "California", value: "California" },
        { name: "Texas", value: "Texas" },
        { name: "Florida", value: "Florida" },
        { name: "New York", value: "New York" },
        { name: "Illinois", value: "Illinois" },
        { name: "Pennsylvania", value: "Pennsylvania" },
        { name: "Ohio", value: "Ohio" },
        { name: "Georgia", value: "Georgia" },
        { name: "North Carolina", value: "North Carolina" },
        { name: "Michigan", value: "Michigan" },
      ],
    },
    {
      name: "Russia",
      value: "Russia",
      states: [
        { name: "Moscow", value: "Moscow" },
        { name: "Saint Petersburg", value: "Saint Petersburg" },
        { name: "Novosibirsk", value: "Novosibirsk" },
        { name: "Yekaterinburg", value: "Yekaterinburg" },
        { name: "Nizhny Novgorod", value: "Nizhny Novgorod" },
        { name: "Kazan", value: "Kazan" },
        { name: "Chelyabinsk", value: "Chelyabinsk" },
        { name: "Samara", value: "Samara" },
        { name: "Omsk", value: "Omsk" },
        { name: "Rostov-on-Don", value: "Rostov-on-Don" },
      ],
    },
  ];
  
  export default countriesData;
  