export const indianStatesAndUTs = [
    {value : "Andhra Pradesh", name :  "Andhra Pradesh", },
    {value : "Arunachal Pradesh", name :  "Arunachal Pradesh", },
    {value : "Assam", name :  "Assam", },
    {value : "Bihar", name :  "Bihar", },
    {value : "Chhattisgarh", name :  "Chhattisgarh", },
    {value : "Goa", name :  "Goa", },
    {value : "Gujarat", name :  "Gujarat", },
    {value : "Haryana", name :  "Haryana", },
    {value : "Himachal Pradesh", name :  "Himachal Pradesh", },
    {value : "Jharkhand", name :  "Jharkhand", },
    {value : "Karnataka", name :  "Karnataka", },
    {value : "Kerala", name :  "Kerala", },
    {value : "Madhya Pradesh", name :  "Madhya Pradesh", },
    {value : "Maharashtra", name :  "Maharashtra", },
    {value : "Manipur", name :  "Manipur", },
    {value : "Meghalaya", name :  "Meghalaya", },
    {value : "Mizoram", name :  "Mizoram", },
    {value : "Nagaland", name :  "Nagaland", },
    {value : "Odisha", name :  "Odisha", },
    {value : "Punjab", name :  "Punjab", },
    {value : "Rajasthan", name :  "Rajasthan", },
    {value : "Sikkim", name :  "Sikkim", },
    {value : "Tamil Nadu", name :  "Tamil Nadu", },
    {value : "Telangana", name :  "Telangana", },
    {value : "Tripura", name :  "Tripura", },
    {value : "Uttar Pradesh", name :  "Uttar Pradesh", },
    {value : "Uttarakhand", name :  "Uttarakhand", },
    {value : "West Bengal", name :  "West Bengal", },
    {value : "Andaman and Nicobar Islands", name :  "Andaman and Nicobar Islands", },
    {value : "Chandigarh", name :  "Chandigarh", },
    {value : "Dadra and Nagar Haveli and Daman and Diu", name :  "Dadra and Nagar Haveli and Daman and Diu", },
    {value : "Lakshadweep", name :  "Lakshadweep", },
    {value : "Delhi", name :  "Delhi", },
    {value : "Puducherry", name :  "Puducherry", },
    {value : "Ladakh", name :  "Ladakh", },
    {value : "Jammu and Kashmir", name :  "Jammu and Kashmir" },
  ];
  